sudo: required
service:
    - docker

before_install:
    - docker build -t rahul/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rahul/docker-react npm run test
      
deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-118838050396"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    # http://dockerreact-env.eba-smhmnnha.ap-southeast-1.elasticbeanstalk.com/
    # arn:aws:s3:::elasticbeanstalk-ap-southeast-1-118838050396